title: Bootstrap OER
description: An OER-theme for Jekyll based on Bootstrap 5

author: 
  name: Christian Glahn
  email: christian.glahn@zhaw.ch

markdown: kramdown
kramdown:
  input: GFM

exclude: 
  - contrib/
  - _contrib/
  - Gemfile
  - Gemfile.lock
